### ISSUE TITLE
How do you debug the code?

### ISSUE THREAD

**Issue by foragerDev** [KamalDevelopers/GevOS#5]
I am trying understand How did you Implement Mouse Driver, And I am trying to add functionality of 2 double click, and Right, left and wheel button. But I am not able to Debug the code to go through step by step to understand how code works.

**Comment by DevGev** [comment]
You could debug GevOS through any debugging tool such as gdb. However I generally don't use debuggers instead I tend to use the klog() function (Kernel Log) to print values through the qemu serial port. It's your choice if you want to use a debugger or not.

**Comment by Edersteiner** [comment]
Using GDB might be hard, you would probably need to implement some features in GevOS to make that work. OSdev wiki should have articles about GDB

**Comment by foragerDev** [comment]
yeah, sure, if you could write about that.
